Repository mnnkhndlwl/mern_youtube_clone, pull requests merged in 2023-03, with the labels that each got.

#55 Fixes #52 [`Share Button`]
  client/package-lock.json
  client/package.json
  client/src/index.js
  client/src/pages/Video.jsx
Labels: Hard, JWOC

#59 [UPDATE] : Sidebar Responsive
  client/src/App.js
  client/src/components/Menu.jsx
  client/src/components/Navbar.jsx
  client/src/pages/Home.jsx
Labels: Hard, JWOC

#63 Fixed bugs
  client/public/index.html
  client/public/logo.png
  client/src/components/Menu.jsx
Labels: Easy, JWOC

#66 Closes #37 `Feature/SuperUser`
  client/src/components/Comment.jsx
  client/src/pages/Video.jsx
  server/controllers/comment.js
  server/controllers/video.js
  server/models/User.js
Labels: Hard, JWOC

#67 Mobile Responsive
  client/src/App.js
  client/src/components/Card.jsx
  client/src/components/Comments.jsx
  client/src/components/Navbar.jsx
  client/src/pages/Home.jsx
  client/src/pages/Video.jsx
Labels: Hard, JWOC

#68 Added loading spinner in video
  client/src/components/Card.jsx
  client/src/pages/Video.jsx
Labels: Easy, JWOC

#71 Two video components on video page is solved
  client/src/pages/Video.jsx
Labels: Medium, JWOC

#76 Closes #74 `Feature/VoiceSearch`
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Navbar.jsx
Labels: Hard, JWOC

#78 Changes is made in video component
  client/src/pages/Video.jsx
Labels: Hard, JWOC

#79 online status shown using isOnline library
  client/package-lock.json
  client/package.json
  client/src/utils/useNetworkStatus.js
Labels: Hard, JWOC
