Repository mnnkhndlwl/mern_youtube_clone, pull requests merged in 2023-02, with the labels that each got.

#16 added space between text and video
  client/src/components/Card.jsx
  package-lock.json
Labels: Easy, JWOC

#22 centered loading spinner
  client/src/pages/SignIn.jsx
  client/src/utils/spinner.jsx
Labels: Easy, JWOC

#25 Improved Documentation
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: Medium, JWOC

#29 freshcommit
  client/src/pages/Home.jsx
Labels: Medium, JWOC

#30 added hover effects
  client/src/components/Card.jsx
Labels: Easy, JWOC

#32 Fully changed and beautified README.md
  LICENSE
  README.md
Labels: Medium, JWOC

#33 added cross icon in error of signin page
  client/src/pages/SignIn.jsx
  client/src/utils/errorMessage.jsx
Labels: Medium, JWOC

#35 message shown if user is offline
  client/src/App.js
  client/src/utils/useNetworkStatus.js
Labels: Hard, JWOC

#36 Centred the spinner
  client/src/pages/Search.jsx
  client/src/utils/spinsearch.jsx
  client/src/utils/spinsearch2.css
Labels: Easy, JWOC

#39 add profile page in youtube clone
  client/public/index.html
  client/public/logo.jpeg
  client/src/App.js
  client/src/assests/images/Avatar.png
  client/src/components/Model.jsx
  client/src/components/Navbar.jsx
  client/src/firebase.js
  client/src/index.css
  client/src/index.js
  client/src/pages/Profile.jsx
  client/src/utils/Theme.js
Labels: Hard, JWOC

#41 added effects in search and made like real youtube
  client/src/components/Navbar.jsx
Labels: Easy, JWOC

#42 [Update]: Added Z-index in Navbar
  client/src/components/Navbar.jsx
Labels: Easy, JWOC

#45 #5 issue- Create a custom scrollbar
  client/public/index.html
Labels: Medium, JWOC

#46 [Bug fix] Fixed bottom scrollbar bug
  client/src/index.css
Labels: Easy, JWOC

#48 alert message pops if user is not signed in and trying to subscribe
  client/src/pages/Video.jsx
Labels: Medium, JWOC

#54 if user is subscribed then subscribed button should be shown in grey colour other wise it should be red #51
  client/src/pages/Video.jsx
Labels: Easy, JWOC
